---
version: '3.8'

services:
    base-php:
        &base-php
        platform: linux/x86_64
        env_file: apps/back/.env
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        command: [ "true" ]
    composer-install:
        <<: *base-php
        volumes:
            - ./apps:/usr/src/app
            - ./apps/back/vendor:/usr/src/app/vendor
        working_dir: /usr/src/app
        command: [ "composer", "install" ]
        profiles: ["composer"]
    php:
        <<: *base-php
        volumes:
            - './apps/back:/usr/src/app'
            - './apps/back/.env:/usr/src/app/.env'
        restart: unless-stopped
        command: [ "php-fpm" ]
        depends_on:
            db:
              condition: service_healthy
    nginx:
        image: nginx:1.21.3-alpine
        ports:
            - 80:80
        volumes:
            - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./apps/back/public:/usr/src/app/public
        restart: unless-stopped
    db:
        image: mysql:8.0.32
        restart: unless-stopped
        volumes:
          - db:/var/lib/mysql
        healthcheck:
          test: [CMD, mysqladmin, ping, --silent]
        environment:
          - MYSQL_RANDOM_ROOT_PASSWORD=yes
          - MYSQL_DATABASE=quipaiequoi
          - MYSQL_USER=admin
          - MYSQL_PASSWORD=No!ss@r2022
    adminer:
        image: adminer
        restart: unless-stopped
        ports:
            - 8080:8080
volumes:
    db:
